package com.wealthwise.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.wealthwise.model.NavHistory;
import com.wealthwise.model.Scheme;
import com.wealthwise.parser.NavAllTxtParser;
import com.wealthwise.repository.NavHistoryRepository;
import com.wealthwise.repository.SchemeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.scheduling.annotation.Async;
import org.springframework.scheduling.annotation.EnableAsync;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CompletableFuture;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * On-demand NAV Service
 * ─────────────────────
 * Fetches NAV data ONLY for schemes users actually interact with.
 * Uses Caffeine cache (Redis-style TTL) to avoid repeat calls:
 *
 *   nav_latest:{amfiCode}      → Latest NAV (24h TTL)
 *   nav_history:{amfiCode}     → Full history JSON from mfapi.in (7d TTL)
 *
 * Do NOT fetch all 45k schemes. Only fetch when user selects a scheme.
 */
@Service
@EnableAsync
public class NavService {

    private static final Logger log = LoggerFactory.getLogger(NavService.class);
    private static final String MFAPI_BASE = "https://api.mfapi.in/mf/";
    private static final DateTimeFormatter MFAPI_DATE = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    private static final DateTimeFormatter AMFI_DATE  = DateTimeFormatter.ofPattern("dd-MMM-yyyy");

    // Prevents duplicate concurrent HTTP calls for the same scheme code.
    // If thread B asks for code X while thread A is already fetching X,
    // thread B's CompletableFuture joins thread A's result instead of
    // making a second HTTP call to mfapi.in.
    private final ConcurrentHashMap<String, CompletableFuture<List<Map<String, String>>>>
        inflight = new ConcurrentHashMap<>();

    private final ObjectMapper objectMapper = new ObjectMapper();
    private final RestTemplate restTemplate = new RestTemplate();

    @Autowired
    private SchemeRepository schemeRepo;

    @Autowired
    private NavHistoryRepository navHistoryRepo;

    // ─── Latest NAV (24h cache) ───────────────────────────────────────────────

    /**
     * Returns {nav, date} for a scheme's latest NAV.
     * Priority: cache → mfapi.in → scheme_master (fallback)
     */
    @Cacheable(value = "nav_latest", key = "#amfiCode")
    public Map<String, Object> getLatestNav(String amfiCode) {
        // Synthetic codes (WW_ISIN_*, WW_*) were generated by CAS import and do not exist in mfapi.in
        if (amfiCode == null || amfiCode.startsWith("WW_")) {
            return Map.of("amfiCode", amfiCode != null ? amfiCode : "", "nav", (Object)null, "date", (Object)null, "source", "synthetic_skip");
        }
        log.info("[NAV] Fetching latest NAV for " + amfiCode);
        // Try mfapi.in first (most up-to-date)
        try {
            Map<String, Object> history = fetchFromMfApi(amfiCode);
            if (history != null && history.containsKey("latestNav")) {
                return Map.of(
                    "amfiCode", amfiCode,
                    "nav", history.get("latestNav"),
                    "date", history.get("latestDate"),
                    "source", "mfapi.in"
                );
            }
        } catch (Exception e) {
            log.warn("[NAV] mfapi.in failed for {}: {}", amfiCode, e.getMessage());
        }

        // Fallback to scheme_master
        return schemeRepo.findByAmfiCode(amfiCode).map(s -> {
            Map<String, Object> result = new HashMap<>();
            result.put("amfiCode", amfiCode);
            result.put("nav", s.getLastNav());
            result.put("date", s.getLastNavDate());
            result.put("source", "db_fallback");
            return result;
        }).orElse(Map.of("amfiCode", amfiCode, "nav", null, "date", null, "source", "not_found"));
    }

    /**
     * Force-refresh NAV for a scheme (bypasses cache — updates it).
     * Call this when user adds a new scheme to a transaction.
     */
    @CachePut(value = "nav_latest", key = "#amfiCode")
    public Map<String, Object> refreshLatestNav(String amfiCode) {
        // Same as getLatestNav but @CachePut always runs and updates cache
        log.info("[NAV] Force-refreshing NAV for " + amfiCode);
        try {
            Map<String, Object> history = fetchFromMfApi(amfiCode);
            if (history != null && history.containsKey("latestNav")) {
                // Also update scheme_master in DB
                schemeRepo.findByAmfiCode(amfiCode).ifPresent(s -> {
                    try {
                        Object navObj = history.get("latestNav");
                        if (navObj != null) {
                            s.setLastNav(new BigDecimal(navObj.toString()));
                            Object dateObj = history.get("latestDate");
                            if (dateObj != null) {
                                s.setLastNavDate(LocalDate.parse(dateObj.toString(), MFAPI_DATE));
                            }
                            schemeRepo.save(s);
                        }
                    } catch (Exception e) {
            log.warn("[NAV] Could not update scheme_master for {}", amfiCode);
                    }
                });
                return Map.of(
                    "amfiCode", amfiCode,
                    "nav", history.get("latestNav"),
                    "date", history.get("latestDate"),
                    "source", "mfapi.in"
                );
            }
        } catch (Exception e) {
            log.warn("[NAV] Refresh failed for {}: {}", amfiCode, e.getMessage());
        }
        return getLatestNav(amfiCode);
    }

    // ─── Historical NAV for a specific date ──────────────────────────────────

    /**
     * Returns the full historical NAV list for a scheme.
     *
     * Strategy — DB-first, always-serve-immediately:
     *   1. If we have data in DB → serve it IMMEDIATELY (even if stale).
     *      If stale (> 7 days), trigger an ASYNC background refresh so future
     *      calls see fresh data without blocking the current response.
     *   2. If no DB data → check inflight map to avoid duplicate HTTP calls;
     *      fetch from mfapi.in synchronously (unavoidable on first load),
     *      persist to DB, return.
     *
     * Result: after the very first fetch, every subsequent call (even after
     * server restart) returns in < 100ms from the DB.
     */
    @Cacheable(value = "nav_history", key = "#amfiCode")
    public List<Map<String, String>> getHistoricalNavs(String amfiCode) {
        // Synthetic codes (WW_ISIN_*, WW_*) do not exist in mfapi.in — skip immediately
        if (amfiCode == null || amfiCode.startsWith("WW_")) {
            log.debug("[NAV] Skipping synthetic scheme code: {}", amfiCode);
            return Collections.emptyList();
        }

        // ── Step 1: Try DB first — ALWAYS serve immediately ───────────────────
        if (navHistoryRepo.existsByAmfiCode(amfiCode)) {
            List<NavHistory> dbRows = navHistoryRepo.findByAmfiCodeOrderByNavDateDesc(amfiCode);
            if (!dbRows.isEmpty()) {
                LocalDate latestStored = dbRows.get(0).getNavDate();
                boolean isStale = latestStored.isBefore(LocalDate.now().minusDays(7));
                List<Map<String, String>> result = convertDbRowsToApiFormat(dbRows);

                if (isStale) {
                    log.info("[NAV] Serving stale DB data for {} ({} records, latest: {}) — refreshing async",
                        amfiCode, dbRows.size(), latestStored);
                    // Non-blocking: refresh in background, don't make the user wait
                    asyncRefreshNavHistory(amfiCode);
                } else {
                    log.info("[NAV] Serving fresh DB data for {} ({} records, latest: {})",
                        amfiCode, dbRows.size(), latestStored);
                }
                return result; // ← RETURN IMMEDIATELY in both cases
            }
        }

        // ── Step 2: No DB data — must fetch synchronously (first time only) ───
        // Use inflight map to prevent N duplicate mfapi.in calls when N requests
        // arrive simultaneously for the same scheme (e.g. dashboard first open).
        log.info("[NAV] No DB data for {} — fetching from mfapi.in (first load)", amfiCode);
        CompletableFuture<List<Map<String, String>>> pending =
            inflight.computeIfAbsent(amfiCode, code -> CompletableFuture.supplyAsync(() -> {
                try {
                    Map<String, Object> apiData = fetchFromMfApi(code);
                    if (apiData != null && apiData.containsKey("data")) {
                        @SuppressWarnings("unchecked")
                        List<Map<String, String>> data = (List<Map<String, String>>) apiData.get("data");
                        persistNavHistoryToDB(code, data);
                        return data;
                    }
                } catch (Exception e) {
                    log.warn("[NAV] First-time fetch failed for {}: {}", code, e.getMessage());
                } finally {
                    inflight.remove(code);
                }
                return Collections.emptyList();
            }));

        try {
            return pending.get(); // wait for completion (unavoidable on first load)
        } catch (Exception e) {
            log.warn("[NAV] Fetch join failed for {}: {}", amfiCode, e.getMessage());
            return Collections.emptyList();
        }
    }

    /**
     * Async background refresh — updates DB + evicts Caffeine cache entry
     * so the next call picks up fresh data. Runs on Spring's async executor.
     */
    @Async
    @CacheEvict(value = "nav_history", key = "#amfiCode")
    public void asyncRefreshNavHistory(String amfiCode) {
        if (amfiCode == null || amfiCode.startsWith("WW_")) return;
        // Skip if another refresh is already in progress
        if (inflight.containsKey(amfiCode + "_refresh")) return;
        inflight.put(amfiCode + "_refresh", CompletableFuture.completedFuture(null));
        try {
            log.info("[NAV] [ASYNC] Refreshing NAV history for {}", amfiCode);
            Map<String, Object> apiData = fetchFromMfApi(amfiCode);
            if (apiData != null && apiData.containsKey("data")) {
                @SuppressWarnings("unchecked")
                List<Map<String, String>> data = (List<Map<String, String>>) apiData.get("data");
                persistNavHistoryToDB(amfiCode, data);
                log.info("[NAV] [ASYNC] Refresh complete for {} ({} records)", amfiCode, data.size());
            }
        } catch (Exception e) {
            log.warn("[NAV] [ASYNC] Refresh failed for {}: {}", amfiCode, e.getMessage());
        } finally {
            inflight.remove(amfiCode + "_refresh");
        }
    }

    /**
     * Converts DB NavHistory rows to the {date, nav} map format used throughout the backend.
     * mfapi.in returns dates as dd-MM-yyyy, so we format the same way.
     */
    private List<Map<String, String>> convertDbRowsToApiFormat(List<NavHistory> rows) {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        List<Map<String, String>> result = new ArrayList<>();
        for (NavHistory row : rows) {
            Map<String, String> entry = new HashMap<>();
            entry.put("date", row.getNavDate().format(fmt));
            entry.put("nav", row.getNavValue().toPlainString());
            result.add(entry);
        }
        return result;
    }

    /**
     * Persists NAV history to DB using native INSERT ON CONFLICT DO NOTHING.
     * This is atomic and eliminates duplicate key violations under concurrent
     * requests (race condition where multiple threads all miss the cache).
     */
    @Transactional
    public void persistNavHistoryToDB(String amfiCode, List<Map<String, String>> data) {
        if (data == null || data.isEmpty()) return;
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        int saved = 0;
        for (Map<String, String> entry : data) {
            String dateStr = entry.getOrDefault("date", "");
            String navStr  = entry.getOrDefault("nav", "");
            if (dateStr.isEmpty() || navStr.isEmpty()) continue;
            try {
                LocalDate navDate = LocalDate.parse(dateStr, fmt);
                BigDecimal navVal = new BigDecimal(navStr);
                // Use native upsert-ignore: atomic, no race condition
                int rows = navHistoryRepo.upsertIgnore(amfiCode, navDate, navVal);
                saved += rows;
            } catch (Exception e) {
                // Skip malformed entries silently
            }
        }
        if (saved > 0) {
            log.info("[NAV] Persisted {} new NAV records to DB for {}", saved, amfiCode);
        }
    }

    /**
     * Get NAV for a specific date string (dd-MM-yyyy or dd-MMM-yyyy).
     * Searches cached history. Returns null if not found.
     */
    public BigDecimal getNavForDate(String amfiCode, String dateStr) {
        List<Map<String, String>> history = getHistoricalNavs(amfiCode);
        // Normalize date to dd-MM-yyyy (mfapi format)
        String lookupDate = normalizeDateString(dateStr);
        for (Map<String, String> entry : history) {
            String entryDate = entry.getOrDefault("date", "");
            String entryNav = entry.getOrDefault("nav", "");
            if (entryDate.equals(lookupDate) || entryDate.equals(dateStr)) {
                try { return new BigDecimal(entryNav); } catch (Exception e) { return null; }
            }
        }
        // Not found on that exact date (holiday/weekend) — find nearest previous business day
        return findNearestNav(history, lookupDate);
    }

    // ─── On-demand scheme registration ───────────────────────────────────────

    /**
     * Called when a user first adds a scheme to a transaction.
     * If the scheme doesn't exist in scheme_master yet, creates a minimal record
     * and triggers a NAV fetch. This avoids needing the full seed.
     */
    public Scheme ensureSchemeExists(String amfiCode) {
        // Check if already in DB
        Optional<Scheme> existing = schemeRepo.findByAmfiCode(amfiCode);
        if (existing.isPresent()) {
            Scheme s = existing.get();
            // Re-enrich from mfapi.in if category is missing or still OTHER
            boolean needsEnrich = s.getBroadCategory() == null
                || s.getBroadCategory().isBlank()
                || "OTHER".equalsIgnoreCase(s.getBroadCategory())
                || "UNKNOWN".equalsIgnoreCase(s.getBroadCategory());
            if (needsEnrich) {
                try {
                    Map<String, Object> apiData = fetchFromMfApi(amfiCode);
                    if (apiData != null) {
                        @SuppressWarnings("unchecked")
                        Map<String, String> meta = (Map<String, String>) apiData.get("meta");
                        if (meta != null) {
                            String sebiCat = meta.getOrDefault("scheme_category", s.getSebiCategory());
                            String type    = meta.getOrDefault("scheme_type", "");
                            String broad   = inferBroadCategory(type, sebiCat);
                            if (!"OTHER".equalsIgnoreCase(broad)) {
                                s.setSebiCategory(sebiCat);
                                s.setBroadCategory(broad);
                                if (s.getSchemeName() == null || s.getSchemeName().startsWith("Scheme "))
                                    s.setSchemeName(meta.getOrDefault("scheme_name", s.getSchemeName()));
                                schemeRepo.save(s);
                                log.info("[NAV] Re-enriched " + amfiCode + " → " + broad + " / " + sebiCat);
                            }
                        }
                    }
                } catch (Exception e) {
            log.warn("[NAV] Re-enrich failed for {}: {}", amfiCode, e.getMessage());
                }
            }
            return s;
        }

        // Not in DB — fetch from mfapi.in and create
        try {
            Map<String, Object> apiData = fetchFromMfApi(amfiCode);
            if (apiData != null) {
                Scheme s = new Scheme();
                s.setAmfiCode(amfiCode);
                @SuppressWarnings("unchecked")
                Map<String, String> meta = (Map<String, String>) apiData.get("meta");
                if (meta != null) {
                    s.setSchemeName(meta.getOrDefault("scheme_name", "Scheme " + amfiCode));
                    s.setAmcName(meta.getOrDefault("fund_house", "Unknown AMC"));
                    s.setSebiCategory(meta.getOrDefault("scheme_category", null));
                    String type = meta.getOrDefault("scheme_type", "");
                    String broad = inferBroadCategory(type, s.getSebiCategory());
                    s.setBroadCategory(broad);
                    s.setFundType("OPEN_ENDED");
                    s.setPlanType(inferPlanType(s.getSchemeName()));
                    s.setOptionType(inferOptionType(s.getSchemeName()));
                    // Derive riskLevel immediately (no need to wait for AMFI seed)
                    try {
                        Integer risk = NavAllTxtParser.assignRiskLevel(s.getSebiCategory(), broad);
                        s.setRiskLevel(risk);
                    } catch (Exception ignored) {}
                }
                if (apiData.containsKey("latestNav")) {
                    try { s.setLastNav(new BigDecimal(apiData.get("latestNav").toString())); } catch (Exception ignored) {}
                }
                if (apiData.containsKey("latestDate")) {
                    try { s.setLastNavDate(LocalDate.parse(apiData.get("latestDate").toString(), MFAPI_DATE)); } catch (Exception ignored) {}
                }
                s.setIsActive(true);
                return schemeRepo.save(s);
            }
        } catch (Exception e) {
            log.warn("[NAV] ensureSchemeExists failed for {}: {}", amfiCode, e.getMessage());
        }
        // Minimal fallback
        Scheme s = new Scheme();
        s.setAmfiCode(amfiCode);
        s.setSchemeName("Scheme " + amfiCode);
        s.setIsActive(true);
        return schemeRepo.save(s);
    }

    // ─── mfapi.in HTTP fetcher (Jackson + RestTemplate) ──────────────────────

    /**
     * Fetches full NAV data from mfapi.in using Jackson for JSON parsing.
     * RestTemplate is already on the classpath via spring-boot-starter-web.
     * Returns a map with: meta (scheme_name, fund_house, etc.), data (list of date+nav),
     * latestNav, latestDate.
     */
    @SuppressWarnings("unchecked")
    private Map<String, Object> fetchFromMfApi(String amfiCode) throws Exception {
        String url = MFAPI_BASE + amfiCode;
        String json = restTemplate.getForObject(url, String.class);
        if (json == null || json.isBlank()) return null;

        JsonNode root  = objectMapper.readTree(json);
        Map<String, Object> result = new HashMap<>();

        // ── meta block ────────────────────────────────────────────────────────
        JsonNode metaNode = root.path("meta");
        if (!metaNode.isMissingNode()) {
            Map<String, String> meta = new HashMap<>();
            metaNode.fields().forEachRemaining(e -> meta.put(e.getKey(), e.getValue().asText()));
            result.put("meta", meta);
        }

        // ── data array (newest entry first in mfapi.in response) ──────────────
        JsonNode dataNode = root.path("data");
        if (dataNode.isArray() && dataNode.size() > 0) {
            List<Map<String, String>> dataList = new ArrayList<>();
            for (JsonNode entry : dataNode) {
                Map<String, String> row = new HashMap<>();
                row.put("date", entry.path("date").asText());
                row.put("nav",  entry.path("nav").asText());
                dataList.add(row);
            }
            result.put("data", dataList);
            result.put("latestNav",  dataList.get(0).get("nav"));
            result.put("latestDate", dataList.get(0).get("date"));
        }

        return result;
    }

    private BigDecimal findNearestNav(List<Map<String, String>> history, String targetDate) {
        // History is newest-first; find the entry just after the target date
        for (Map<String, String> entry : history) {
            String d = entry.getOrDefault("date", "");
            if (d.compareTo(targetDate) <= 0) { // d is on or before target
                try { return new BigDecimal(entry.getOrDefault("nav", "")); } catch (Exception e) { return null; }
            }
        }
        return null;
    }

    private String normalizeDateString(String dateStr) {
        if (dateStr == null) return "";
        dateStr = dateStr.trim();
        // Convert yyyy-MM-dd to dd-MM-yyyy (mfapi format)
        if (dateStr.matches("\\d{4}-\\d{2}-\\d{2}")) {
            String[] p = dateStr.split("-");
            return p[2] + "-" + p[1] + "-" + p[0];
        }
        // Convert dd-MMM-yyyy to dd-MM-yyyy
        if (dateStr.matches("\\d{2}-[A-Za-z]+-\\d{4}")) {
            try {
                LocalDate d = LocalDate.parse(dateStr, AMFI_DATE);
                return d.format(DateTimeFormatter.ofPattern("dd-MM-yyyy"));
            } catch (Exception e) { return dateStr; }
        }
        return dateStr;
    }

    private String inferBroadCategory(String type, String category) {
        if (type == null && category == null) return "OTHER";
        String combined = ((type != null ? type : "") + " " + (category != null ? category : "")).toUpperCase();

        // ── Equity ──────────────────────────────────────────────────────────
        if (combined.contains("EQUITY") || combined.contains("ELSS")
                || combined.contains("LARGE CAP") || combined.contains("MID CAP")
                || combined.contains("SMALL CAP") || combined.contains("MULTI CAP")
                || combined.contains("FLEXI CAP") || combined.contains("FOCUSED")
                || combined.contains("VALUE") || combined.contains("CONTRA")
                || combined.contains("DIVIDEND YIELD") || combined.contains("SECTORAL")
                || combined.contains("THEMATIC") || combined.contains("INDEX FUND")
                || combined.contains("ETF"))                          return "EQUITY";

        // ── Debt — includes Fixed Term / FMP / Interval / Close Ended ───────
        if (combined.contains("DEBT") || combined.contains("LIQUID")
                || combined.contains("MONEY MARKET") || combined.contains("OVERNIGHT")
                || combined.contains("ULTRA SHORT") || combined.contains("LOW DURATION")
                || combined.contains("SHORT DURATION") || combined.contains("MEDIUM DURATION")
                || combined.contains("MEDIUM TO LONG") || combined.contains("LONG DURATION")
                || combined.contains("DYNAMIC BOND") || combined.contains("CORPORATE BOND")
                || combined.contains("CREDIT RISK") || combined.contains("BANKING AND PSU")
                || combined.contains("BANKING & PSU") || combined.contains("GILT")
                || combined.contains("FIXED TERM") || combined.contains("FMP")
                || combined.contains("FIXED MATURITY") || combined.contains("INTERVAL")
                || combined.contains("CLOSE ENDED") || combined.contains("FLOATER")
                || combined.contains("INCOME"))                        return "DEBT";

        // ── Hybrid ──────────────────────────────────────────────────────────
        if (combined.contains("HYBRID") || combined.contains("BALANCED")
                || combined.contains("ARBITRAGE") || combined.contains("EQUITY SAVINGS")
                || combined.contains("MULTI ASSET"))                   return "HYBRID";

        // ── Solution ────────────────────────────────────────────────────────
        if (combined.contains("SOLUTION") || combined.contains("CHILDREN")
                || combined.contains("RETIRE"))                        return "SOLUTION";

        return "OTHER";
    }

    private String inferPlanType(String name) {
        if (name == null) return "UNKNOWN";
        if (name.toUpperCase().contains("DIRECT")) return "DIRECT";
        if (name.toUpperCase().contains("REGULAR")) return "REGULAR";
        return "UNKNOWN";
    }

    private String inferOptionType(String name) {
        if (name == null) return "UNKNOWN";
        String u = name.toUpperCase();
        if (u.contains("IDCW REINVEST") || u.contains("DIVIDEND REINVEST")) return "IDCW_REINVESTMENT";
        if (u.contains("IDCW") || u.contains("DIVIDEND") || u.contains("PAYOUT")) return "IDCW_PAYOUT";
        if (u.contains("GROWTH")) return "GROWTH";
        return "UNKNOWN";
    }
}
